# High Availablity Configuration
---
spring:
  profiles: kolkata
eureka:
  instance:
    hostname: kolkata
    #appname: eureka-cluster-kolkata
  client:
    #serviceUrl:
      #defaultZone: http://localhost:8051/eureka
    register-with-eureka: false
    #fetch-registry: true
    #healthcheck:
      #enabled: true
server:
  port: 8050


---
spring:
  profiles: mumbai
eureka:
  instance:
    hostname: mumbai
    #appname: eureka-cluster-mumbai
  client:
    #serviceUrl:
      #defaultZone: http://localhost:8050/eureka
    register-with-eureka: false
    #fetch-registry: true
    #healthcheck:
      #enabled: true    
server:
  port: 8051


---
eureka:
  client:
    serviceUrl:
      defaultZone: http://kolkata:8050/eureka/,http://mumbai:8051/eureka/